version: "3"
services:
  vg-frontend:
    image: vg-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - vg-app
  vg-backend:
    image: vg-backend
    environment:
      PORT: ${5000}
      NODE_ENV: ${NODE_ENV}
      password: ${password}
      DEBUG: ${DEBUG}
      jwtPrivateKey: ${jwtPrivateKey}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}
      MONGO_DB_LOG: ${MONGO_DB_LOG}
      USER_VERIFICATION_TOKEN_SECRET: ${USER_VERIFICATION_TOKEN_SECRET}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - vg-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - vg-app
    volumes:
      - mongo-data:/data/db
networks:
  vg-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
